linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - gci
    - gochecknoinits
    - gomoddirectives
    - ireturn
    - lll
    - nestif
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - varnamelen
    # deprecated
    - bodyclose
    - contextcheck
    - deadcode
    - golint
    - ifshort
    - interfacer
    - maligned
    - nilerr
    - noctx
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - tparallel
    - unparam
    - varcheck
    - wastedassign

linters-settings:
  revive:
    rules:
      - name: line-length-limit
        arguments: [120]

  funlen:
    lines: 100

  gosec:
    excludes:
      - G204

  gomnd:
    settings:
      mnd:
        ignored-numbers: 0o600,0o755,2,10,100,1000,16,32,64,128

  gofumpt:
    lang-version: "1.21"

  nolintlint:
    require-specific: true

issues:
  include:
    - EXC0002

  exclude-rules:
    - path: _test.go
      linters:
        - funlen
        - gocyclo
        - gochecknoglobals
        - gocognit
        - paralleltest
        - dupl
        - maintidx
